services:
  om-nest:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    command: npm run start


  om-react:
    image: node:18-alpine
    volumes:
      - ./frontend:/code/frontend
    ports:
      - '5173:5173'
    command: >
      sh -c "cd code/frontend && npm install && npm run dev --host"
    stdin_open: true
    tty: true

  om-postgresql:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./docker/pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'